#!/usr/bin/env bash

set -euo pipefail

echo ""
echo "Project Scaffold Setup"
echo "======================"
echo ""

# ── Collect project info ──────────────────────────────────────────────────────

# Note: PROJECT_NAME must not contain spaces, forward slashes, or pipe characters.
# Spaces break markdown links; slashes and pipes break sed replacements.

read -p "Project name (e.g. EAGLE, Nexus, Atlas): " PROJECT_NAME

if [ -z "$PROJECT_NAME" ]; then
  echo "Error: project name cannot be empty."
  exit 1
fi

if [[ "$PROJECT_NAME" =~ [[:space:]/\|] ]]; then
  echo "Error: project name must not contain spaces, forward slashes, or pipe characters."
  exit 1
fi

read -p "One-line description: " PROJECT_DESC
read -p "Platform (e.g. Railway, AWS, Vercel): " PROJECT_PLATFORM
read -p "Author name (for LICENSE): " AUTHOR

echo ""
echo "Project type:"
echo "  1) JavaScript / TypeScript (version also tracked in package.json)"
echo "  2) Other (Python, Go, etc. — VERSION file only)"
read -p "Select [1/2]: " PROJECT_TYPE_INPUT

echo ""

DATE=$(date +%Y-%m-%d)
YEAR=$(date +%Y)

# ── Validate PROJECT.md exists ────────────────────────────────────────────────

if [ ! -f "PROJECT.md" ]; then
  echo "Error: PROJECT.md not found. Run this script from the repo root."
  exit 1
fi

# ── Rename PROJECT.md ─────────────────────────────────────────────────────────

mv PROJECT.md "${PROJECT_NAME}.md"

# ── Replace placeholders in all templated files ───────────────────────────────

FILES=(
  "${PROJECT_NAME}.md"
  "CONTRIBUTING.md"
  "CHANGELOG.md"
  "COMMANDS.md"
  "README.template.md"
  "LICENSE"
  "skills/scribe.md"
  "tooling/agent-instructions.md"
  "project-context.md"
)

for FILE in "${FILES[@]}"; do
  if [ -f "$FILE" ]; then
    sed -i.bak \
      -e "s/{{PROJECT_NAME}}/${PROJECT_NAME}/g" \
      -e "s|{{PROJECT_DESCRIPTION}}|${PROJECT_DESC}|g" \
      -e "s/{{PROJECT_PLATFORM}}/${PROJECT_PLATFORM}/g" \
      -e "s/{{DATE}}/${DATE}/g" \
      -e "s/{{YEAR}}/${YEAR}/g" \
      -e "s/{{AUTHOR}}/${AUTHOR}/g" \
      "$FILE"
    rm -f "${FILE}.bak"
  fi
done

# ── Create docs directory ──────────────────────────────────────────────────────

mkdir -p docs
cat > docs/README.md << 'DOCS_README'
# Documentation

This directory is yours. The scaffold has no opinion on how you organise it or what you put in it — structure it however makes sense for your project.

For AI tool instructions and command references, see [`tooling/`](../tooling/).
DOCS_README

# ── Swap READMEs: project README replaces the scaffold README ─────────────────

mv README.template.md README.md

# ── JS/TS: remove package.json row from CONTRIBUTING.md if not applicable ─────

if [ "$PROJECT_TYPE_INPUT" != "1" ]; then
  sed -i.bak '/package.json/d' CONTRIBUTING.md && rm -f CONTRIBUTING.md.bak
fi

# ── Reset VERSION for new project ─────────────────────────────────────────────

echo "0.1.0" > VERSION

# ── Write .scaffold-version from scaffold.json ────────────────────────────────

if [ -f "scaffold.json" ]; then
  SCAFFOLD_VERSION=$(awk -F'"' '/"version"/ { print $4; exit }' scaffold.json)
  echo "$SCAFFOLD_VERSION" > .scaffold-version
fi

# ── Remove scaffold development files ─────────────────────────────────────────

rm -rf .scaffold
rm -f scaffold.json

# ── Generate tool-specific adapter files ─────────────────────────────────────

bash skills/sync.sh

# ── Summary ───────────────────────────────────────────────────────────────────

echo "Done. ${PROJECT_NAME} is ready."
echo ""
echo "Files:"
echo "  README.md                        ← your project README"
echo "  ${PROJECT_NAME}.md               ← fill in your system design"
echo "  COMMANDS.md                      ← command reference, ready to use"
echo "  CONTRIBUTING.md                  ← versioning rules, ready to use"
echo "  CHANGELOG.md                     ← change history, ready to use"
echo "  VERSION                          ← 0.1.0"
echo "  .scaffold-version               ← scaffold version at time of setup"
echo "  LICENSE                          ← MIT, ${YEAR}, ${AUTHOR}"
echo "  docs/                            ← project documentation (grows with the project)"
echo "  bin/project                      ← CLI for read-only commands (no agent needed)"
echo "  bin/update                       ← pull scaffold updates from the template repo"
echo ""
echo "AI tooling (generated by sync.sh):"
echo "  CLAUDE.md                        ← Claude Code (auto-loaded at session start)"
echo "  .github/copilot-instructions.md  ← GitHub Copilot (auto-loaded)"
echo "  .cursor/rules/agent.mdc          ← Cursor (alwaysApply: true)"
echo "  .clinerules                      ← Cline (auto-loaded from project root)"
echo "  .roo/rules/agent.md              ← Roo Code (auto-loaded from .roo/rules/)"
echo "  tooling/agent-instructions.md    ← source of truth — edit this, not the adapters"
echo ""
echo "Next steps:"
echo "  1. Fill in ${PROJECT_NAME}.md with your system design"
echo "  2. Run context:generate in your AI tool to generate project-context.md from ${PROJECT_NAME}.md"
if [ "$PROJECT_TYPE_INPUT" = "1" ]; then
  echo "  3. Set \"version\": \"0.1.0\" in your package.json"
fi
echo ""
echo "When ready to commit:"
echo "  git add ."
echo "  git commit -m \"Initial scaffold\""
echo "  git tag -a v0.1.0 -m \"Release v0.1.0 — initial scaffold\""
echo "  git push origin main"
echo ""
echo "  If no remote is configured yet (fresh git init):"
echo "    git remote add origin <your-repo-url>"
echo "    git push -u origin main"
echo ""

# ── Self-cleanup ──────────────────────────────────────────────────────────────

rm -- "$0"
